fetch_credentials_sandbox_url = "https://services-qa.walgreens.com/api/photo/creds/v3"
credential_endpoint = "/api/util/v3.0/mweb5url"
photo_details_endpoint = "/api/photo/products/v3"
photo_coupons_endpoint = "/api/photo/order/coupon/v3"
photo_stores_endpoint = "/api/photo/store/v3"
submit_photo_order_endpoint = "/api/photo/order/submit/v3"
photo_order_status = "/api/photo/order/status/v3"